### ISSUE TITLE
第46行是不是有一点笔误

### ISSUE THREAD

**Issue by xinyue** [imlinhanchao/ngx_proxy_wiki#2]
第46行原本为
`proxy_redirect https://$subdomain.m.wikipedia.org/ http://m.$subdomain.wiki.yourdomain.com/;`

是不是应该修改为
`proxy_redirect https://$subdomain.m.wikipedia.org/ http://$subdomain.m.wiki.yourdomain.com/;`

**Comment by imlinhanchao** [comment]
感谢指出，已经修正。
